### ISSUE TITLE
Issue #24 – should we use Boolean for the preference or just a controlled vocabulary?

### ISSUE THREAD

**Issue by stephenhart8** [chin-rcip/chin-rcip#24]
Some instances, like appellations, have a E55_Type  to specify if an appellation is the one preferred by the institution or not. This type is therefore binary, either yes, it is a preferred appellation, or no, it is a non-preferred appellation.

There is two way to tackle this:
1. to use a Boolean variable (like yes or no);
2. to use controlled vocabulary (AAT or other).

What should we use? Could we use both?

**Comment by illip** [comment]
Testing.

**Comment by illip** [comment]
Testing

**Comment by illip** [comment]
Testing

**Comment by Habennin** [comment]
Use aat type. The Yes No means nothing in linked data

**Comment by stephenhart8** [comment]
I will close this issue unless someone wants to add something.

**Comment by illip** [comment]
I agree with @Habennin, It's always a better idea to use URIs to foster interoperability. Also, we don't know the future and we might need a third option in certain cases.

+1 for controlled vocabularies

**Comment by stephenhart8** [comment]
In accordance with everyone, we will use Controlled Vocabularies, instead of booleans.
