### ISSUE TITLE
Issue #28 - Does the "Industry" field can be modeled with the occupation pattern?

### ISSUE THREAD

**Issue by stephenhart8** [chin-rcip/chin-rcip#28]
In the v.1.5 of the TM, the Industry field is modeled as a simple `E55 Type` linked directly to the `E39 Actor`.
But I just realized that the `F51 Pursuit` in the [CIDOC extension FRBRoo](http://www.cidoc-crm.org/frbroo/sites/default/files/FRBRoo_V3.0.pdf) has the scope:

> This class comprises periods of continuous activity of an Actor in a specific professional or
creative domain or field

That would simply a lot the model, with the professional activity of a person and a group modeled the same way.

Would that also work with the artistic activity of groups of artists?
For example the Group of Seven is dedicated to the painting of Landscapes. Could the groups have as an `F51 Pursuit` "Landscaping"?

**Comment by KarineLeonardBrouillet** [comment]
I think it does work yes especially considering how the examples `F51 Pursuit` are of artists and a Library

**Comment by Habennin** [comment]
yes it's appropriate

**Comment by stephenhart8** [comment]
If nobody wants to add something, I will close the issue.

**Comment by Habennin** [comment]
+1

**Comment by illip** [comment]
You have my blessing. :)
