### ISSUE TITLE
Issue #35 - Should we date the appellations?

### ISSUE THREAD

**Issue by stephenhart8** [chin-rcip/chin-rcip#35]
I remember that one of the important features for some institutions was to be able to date the appellations.
With [CIDOC FRBRoo](http://www.cidoc-crm.org/frbroo/sites/default/files/FRBRoo_V3.0.pdf), and its event `F52 Name Use Activity`, it would be quite easy to model it.
There's the pattern:
![CiC_Issue35-example1](https://user-images.githubusercontent.com/49342191/69455974-9016d800-0d37-11ea-85a3-44742fdc8100.png)
https://drive.google.com/open?id=1KC_9k25wPLUygNUaBHXNbtAxNLv7Vs8S
The property `R61 occurred in kind of context` allows us to specify in which context the name was used.

Do you think it would be a good pattern to implement in the model?

**Comment by KarineLeonardBrouillet** [comment]
I think it would be useful in some instances such as: 

- An actor changing their name at some point in their life (e.g. I change my name to Eleanor at 45)

- Dating an artist name (e.g. J.K. Rowling who wrote adult books under the name Robert Galbraith)

- Representing changes in scientific knowledge and thus knowing that an appellation is the latest one recognized by a field

**Comment by eecanning** [comment]
+1

**Comment by Habennin** [comment]
+1

**Comment by stephenhart8** [comment]
Agreed by all, it has been implemented in the TM

**Comment by VladimirAlexiev** [comment]
@stephenhart8 @KarineLeonardBrouillet all of that is good.

But does the TM specify "which context" or give examples? In particular, I think you should codify the use of pseudonyms (i.e. have such concept).

And maybe artist duos? Or these are always represented as a small Group?
