### ISSUE TITLE
Issue #5 - Type vs. Activity

### ISSUE THREAD

**Issue by chin-rcip** [chin-rcip/chin-rcip#5]
Stephen Hart Jun 21st at 11:53 AM
As Philippe suggested to me earlier this week while reviewing the data model, the difference is very fin between the Activity modeled like the flourishing dates and the Type of the technique. Other information like school attendance, profession, and other activities may fall into one ore the other category. Therefore, the distinction between what should be a type and what should be an activity is not clear.

Philippe Michon  2 months ago
Both options are possible, we "just" have to make a decision. IMHO, we should try to keep the model as simple as possible and something havin two different approaches is more complicated than keeping a systematic path. On the other hand, if we know where to draw the line between the two options, it's fine. For instance, it could the dating need :slightly_smiling_face:

**Comment by stephenhart8** [comment]
This issue is Cole to the closed issue #1
